# embedded tomcat server port
server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  # Data Source
  datasource:
    url: jdbc:mysql://localhost:3306/admin?useSSL=false
    username: root
    password: root


# 开发环境使用嵌入式h2数据库，无需配置数据源
